[package]
name = "sorting_algorithms"
version = "0.1.0"
authors = ["Chris Farmer <WS311471@weston.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
